site_name: The OpenPM Playbook
site_url: https://OpenPM-Foundry.github.io/The-OpenPM-Playbook/
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
theme:
  name: material